Refactor to use TJ command layout

diff --git a/scratch b/scratch
--- a/scratch
+++ b/scratch
@@ -1,195 +1,194 @@
 #!/bin/sh
-# this script is not entirely posix compliant as it uses 'local' to define
-# function scoped variables. But there are so few shells that don't support it
-# that it may as well be posix.
-
-scratch() {
 
 
-  # define variables to be used in the script
-  # ----------------------------------------------------------------------------
-  local version='0.0.1'
-  local name scratch_dir to_install protocol git_minor_version
+# Variables
+# ------------------------------------------------------------------------------
+version='0.0.1'
+name=
+scratch_dir=
+to_install=
+protocol=
+git_minor_version=
+dot_scratch_dir="$HOME/.scratch/repos"
+
+# set scratch scratch_dir
+scratch_dir=${SCRATCH_DIR:-"$HOME/scratches"}
+
+# set protocol
+protocol=${SCRATCHES_PROTOCOL:-"https"}
 
 
-  # define local functions to be used in the script (unset at the end)
-  # ----------------------------------------------------------------------------
-  __rand_char() {
-    local rand_number=$(__rand_number)
-    local rand_index=$(( $rand_number % $# + 1 ))
-    # this eval is okay because there is no scope for code injection
-    # and the function is unset at the end
-    eval "printf %s \${$rand_index}"
-  }
+# Local Functions
+# ------------------------------------------------------------------------------
+rand_char() {
+  local rand_number=$(rand_number)
+  local rand_index=$(( $rand_number % $# + 1 ))
+  # this eval is okay because there is no scope for code injection
+  # and the function is unset at the end
+  eval "printf %s \${$rand_index}"
+}
 
-  __rand_number() {
-    printf %s $(od -An -tu -N2 /dev/urandom)
-  }
+rand_number() {
+  printf %s $(od -An -tu -N2 /dev/urandom)
+}
 
-  __rand_word() {
-    local word
-    word=$word$(__rand_char qu wh w r t y p ph d dr f g gr h j k kn l z c ch v b bl n m)
-    word=$word$(__rand_char a ai e ee ei ie oo o u)
-    word=$word$(__rand_char w r t y p s d ff g h k l c b n m)
-    printf %s $word
-  }
+rand_word() {
+  local word
+  word=$word$(rand_char qu wh w r t y p ph d dr f g gr h j k kn l z c ch v b bl n m)
+  word=$word$(rand_char a ai e ee ei ie oo o u)
+  word=$word$(rand_char w r t y p s d ff g h k l c b n m)
+  printf %s $word
+}
 
-  __git_version_at_least() {
-    local minor_git_version=$(git --version | sed 's/\(git version \)\([0-9]*\.[0-9]*\)\(.*\)/\2/')
-    echo "$1 < ${minor_git_version}" | bc
-  }
+git_version_at_least() {
+  local minor_git_version=$(git --version | sed 's/\(git version \)\([0-9]*\.[0-9]*\)\(.*\)/\2/')
+  echo "$1 < ${minor_git_version}" | bc
+}
 
-  __extract_repo_info() {
-    local repo
+extract_repo_info() {
+  local repo
 
-    # will extract "username/repo#commit-ish" from the following:
-    #
-    # supercrabtree/kerpow
-    # supercrabtree/kerpow#6c7efc4
-    # git@github.com:supercrabtree/kerpow.git
-    # https://github.com/supercrabtree/kerpow
-    # https://github.com/supercrabtree/kerpow.git
+  # will extract "username/repo#commit-ish" from the following:
+  #
+  # supercrabtree/kerpow
+  # supercrabtree/kerpow#6c7efc4
+  # git@github.com:supercrabtree/kerpow.git
+  # https://github.com/supercrabtree/kerpow
+  # https://github.com/supercrabtree/kerpow.git
 
-    # did they pass in a username/repo
-    # i.e. supercrabtree/beepboop
-    repo=$(printf %s $1 | sed -n 's/\(^[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]\/[a-zA-Z0-9\-]*$\)/\1/p')
-    if [ ! -z $repo ];then
-      printf '%s#' $repo
-      return 0
-    fi
-
-    # did they pass in a username/repo#commit-ish
-    # i.e. supercrabtree/beepboop#6c778ccd
-    repo=$(printf %s $1 | sed -n 's/\(^[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]\/[a-zA-Z0-9\-]*#.*$\)/\1/p')
-    if [ ! -z $repo ];then
-      printf '%s' $repo
-      return 0
-    fi
-
-    # did they pass in an https git repo address
-    # i.e. https://github.com/supercrabtree/beepboop.git                         = supercrabtree/beepboop
-    # or   https://github.com/supercrabtree/beepboop                             = supercrabtree/beepboop
-    # or   https://github.com/supercrabtree/beepboop/so/deep/nested/whatever     = supercrabtree/beepboop
-    repo=$(printf %s $1 | sed -n 's/https\:\/\/github.com\/\([^\/]*\)\/\([^\.\/]*\)\(.*\)/\1\/\2/p')
-    if [ ! -z $repo ];then
-      printf '%s#' $repo
-      return 0
-    fi
-
-    # did they pass in an ssh git repo address
-    # i.e. git@github.com:supercrabtree/beepboop.git = supercrabtree/beepboop
-    repo=$(printf %s $1 | sed -n 's/git@github.com:\([^\/]*\)\/\([^\/]*\)\.git/\1\/\2/p')
-    if [ ! -z $repo ];then
-      printf '%s#' $repo
-      return 0
-    fi
-  }
-
-
-  # run script
-  # ----------------------------------------------------------------------------
-
-  # set scratch scratch_dir
-  scratch_dir=${SCRATCH_DIR:-"$HOME/scratches"}
-
-  # set protocol
-  protocol=${SCRATCHES_PROTOCOL:-"https"}
-
-
-  # if `scratch version`
-  if [ "$1" = "version" ] || [ "$1" = "-v" ]; then
-    printf '%s\n' $version
+  # did they pass in a username/repo
+  # i.e. supercrabtree/beepboop
+  repo=$(printf %s $1 | sed -n 's/\(^[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]\/[a-zA-Z0-9\-]*$\)/\1/p')
+  if [ ! -z $repo ]; then
+    printf '%s#' $repo
     return 0
   fi
 
-  # if its a dir, and writable by this process
-  if [ -d "${scratch_dir}" ]; then
-    if [ ! -w "${scratch_dir}" ]; then
-      printf "\nYour scratch directory %s is not writable. Try:" $scratch_dir
-      printf "  chmod +x %s\n" $scratch_dir
-      return 1
+  # did they pass in a username/repo#commit-ish
+  # i.e. supercrabtree/beepboop#6c778ccd
+  repo=$(printf %s $1 | sed -n 's/\(^[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]\/[a-zA-Z0-9\-]*#.*$\)/\1/p')
+  if [ ! -z $repo ]; then
+    printf '%s' $repo
+    return 0
+  fi
+
+  # did they pass in an https git repo address
+  # i.e. https://github.com/supercrabtree/beepboop.git                         = supercrabtree/beepboop
+  # or   https://github.com/supercrabtree/beepboop                             = supercrabtree/beepboop
+  # or   https://github.com/supercrabtree/beepboop/so/deep/nested/whatever     = supercrabtree/beepboop
+  repo=$(printf %s $1 | sed -n 's/https\:\/\/github.com\/\([^\/]*\)\/\([^\.\/]*\)\(.*\)/\1\/\2/p')
+  if [ ! -z $repo ]; then
+    printf '%s#' $repo
+    return 0
+  fi
+
+  # did they pass in an ssh git repo address
+  # i.e. git@github.com:supercrabtree/beepboop.git = supercrabtree/beepboop
+  repo=$(printf %s $1 | sed -n 's/git@github.com:\([^\/]*\)\/\([^\/]*\)\.git/\1\/\2/p')
+  if [ ! -z $repo ]; then
+    printf '%s#' $repo
+    return 0
+  fi
+}
+
+check_dir_exists() {
+  local dir=$1
+
+  # if its a dir
+  if [ -d "$dir" ]; then
+
+    # but not writable by this process
+    if [ ! -w "$dir" ]; then
+      printf "\nYour scratch directory %s is not writable. Try:" "$dir"
+      printf "  chmod +x %s\n" "$dir"
+      exit 1
     fi
+
+  # or it is not a directory
   else
-    if [ -f "${scratch_dir}" ]; then
-      printf "\nYour scratch directory %s is not a directory\n" $scratch_dir
-      return 1
+
+    # but is instead a file
+    if [ -f "$dir" ]; then
+      printf "\nYour scratch directory %s is not a directory\n" "$dir"
+      exit 1
+
+    # or just doesn't exist
     else
-      mkdir -p $scratch_dir
+      mkdir -p "$dir"
       if [ $? -eq 1 ]; then
-        printf "\nFailed to create %s\n" $scratch_dir
-        return 0
+        printf "\nFailed to create %s\n" "$dir"
+        exit 1
       fi
+      # success! directory now exists
     fi
   fi
+}
 
-  # if no parameters supplied
-  if [ "$#" -eq 0 ]; then
-    name="scratch-$(__rand_word)"
-    cd $scratch_dir &&
-    mkdir -p $name &&
-    cd $name
-    return 0
+
+# Subcommands
+# ------------------------------------------------------------------------------
+version() {
+  printf '%s\n' $version
+}
+
+help() {
+  printf '%s\n' 'usage info is great'
+}
+
+list() {
+  find $dot_scratch_dir -mindepth 2 -maxdepth 2 -print0 | while IFS= read -r -d '' dir; do
+    local username=$(basename $(dirname "$dir"))
+    local repo=$(basename "$dir")
+    printf '%s/%s\n' "$username" "$repo"
+  done
+}
+
+install() {
+  local to_install=$1
+
+  # Die if to_install is empty
+  if [ -z "$to_install" ]; then
+    printf '%s\n' "Erm, what do you want to install? (You need another parameter)"
+    exit 1
   fi
 
-  # if `scratch install`
-  if [ "$1" = "install" ]; then
-
-    local to_install=$2
-
-    # Check to make sure the next parameter has also been supplied
-    if [ "$#" -eq 1 ];then
-      printf '%s\n' "Erm, what do you want to install? (You need another parameter)"
-      return 1
-    fi
-
-    # if to_install is a local path
-    if [ -d $to_install ];then
-      printf '%s\n' "Stop the press!! it's a folder. Sorry not supported yet."
-      return 0
-    fi
-
-    local repo_info=$(__extract_repo_info $to_install)
-    local repo_name=$(printf %s $repo_info | sed 's/#.*//')
-    local repo_commit_ish=$(printf %s $repo_info | sed 's/.*#//')
-
-    url_format="https://git::@github.com/$repository_name.git"
-
-    if [ $(__git_version_at_least 2.3) -eq 1 ]; then
-      # Git 2.3.0 introduced $GIT_TERMINAL_PROMPT
-      # which can be used to suppress user prompt
-      export GIT_TERMINAL_PROMPT=0
-      url_format="https://github.com/$repo_name.git"
-    fi
-
-    if [ $protocol = "https" ]; then
-      url_format="https://git::@github.com/$repo_name.git"
-    elif [ $protocol = "ssh" ]; then
-      url_format="git@github.com:$repo_name.git"
-    fi
-
-
-    if [ ! -z $repo_commit_ish ]; then
-      git clone --recursive $url_format "$HOME/.scratch/repos/$repo_name#$repo_commit_ish"
-      $(cd "$HOME/.scratch/repos/$repo_name#$repo_commit_ish"; git checkout --quiet $repo_commit_ish)
-      printf '\n%s\n  %s' "Successfully installed $repo_name#$repo_commit_ish. To use it right now:" "scratch $(basename $repo_name)"
-    else
-      git clone --recursive $url_format "$HOME/.scratch/repos/$repo_name"
-      printf '\n%s\n  %s' "Successfully installed $repo_name. To use it right now:" "scratch $(basename $repo_name)"
-    fi
-    return 0
+  # Die if to_install is a local folder
+  if [ -d $to_install ]; then
+    printf '%s\n' "Stop the press!! it's a folder. Sorry not supported yet."
+    exit 1
   fi
 
-  # if `scratch list`
-  if [ $1 = "list" ]; then
-    find "$HOME/.scratch/repos" -mindepth 2 -maxdepth 2 -print0 | while IFS= read -r -d '' folder; do
-      local dirname=$(basename $(dirname "$folder"))
-      local basename=$(basename "$folder")
-      printf '%s/%s\n' "$dirname" "$basename"
-    done
-    return 0
+  local repo_info=$(extract_repo_info $to_install)
+  local repo_name=$(printf %s $repo_info | sed 's/#.*//')
+  local repo_commit_ish=$(printf %s $repo_info | sed 's/.*#//')
+
+  url_format="https://git::@github.com/$repository_name.git"
+
+  if [ $(git_version_at_least 2.3) -eq 1 ]; then
+    # Git 2.3.0 introduced $GIT_TERMINAL_PROMPT
+    # which can be used to suppress user prompt
+    export GIT_TERMINAL_PROMPT=0
+    url_format="https://github.com/$repo_name.git"
   fi
 
-  # if `scratch $plugin-that-is-installed`
+  if [ $protocol = "https" ]; then
+    url_format="https://git::@github.com/$repo_name.git"
+  elif [ $protocol = "ssh" ]; then
+    url_format="git@github.com:$repo_name.git"
+  fi
+
+  if [ ! -z $repo_commit_ish ]; then
+    git clone --recursive $url_format "$HOME/.scratch/repos/$repo_name#$repo_commit_ish"
+    $(cd "$HOME/.scratch/repos/$repo_name#$repo_commit_ish"; git checkout --quiet $repo_commit_ish)
+    printf '\n%s\n  %s' "Successfully installed $repo_name#$repo_commit_ish. To use it right now:" "scratch $(basename $repo_name)"
+  else
+    git clone --recursive $url_format "$HOME/.scratch/repos/$repo_name"
+    printf '\n%s\n  %s' "Successfully installed $repo_name. To use it right now:" "scratch $(basename $repo_name)"
+  fi
+  return 0
+}
+
+scratch_installed() {
   if [ ! -z $1 ]; then
     installed=""
     find "$HOME/.scratch/repos" -mindepth 2 -maxdepth 2 -print0 | while IFS= read -r -d '' dir; do
@@ -208,18 +207,36 @@ scratch() {
 
     if [ "$number_of_matches" -eq 1 ]; then
       to_scratch="$(echo $matches | xargs | sed -e 's/ /\//' -e 's/ /#/')"
-      name="scratch-$1-$(__rand_word)"
+      name="scratch-$1-$(rand_word)"
       $(cd $scratch_dir && mkdir -p $name)
       cd "$scratch_dir/$name" && cp -R "$HOME/.scratch/repos/$to_scratch/" . && rm -rf .git
       return 0
     fi
-
   fi
-
-  unset -f __rand_char
-  unset -f __rand_word
-  unset -f __rand_number
-  unset -f __git_version_at_least
-  unset -f __extract_repo_info
 }
+
+
+# Scratch command
+# ------------------------------------------------------------------------------
+scratch() {
+  name="scratch-$(rand_word)"
+  cd $scratch_dir &&
+  mkdir -p $name &&
+  cd $name
+  return 0
+}
+
+
+# Pass argv
+# ------------------------------------------------------------------------------
+while test $# -ne 0; do
+  arg=$1; shift
+  case $arg in
+    -h|--help)    help;                 exit;;
+    -v|--version) version;              exit;;
+    list)         list;                 exit;;
+    install)      install $@;           exit;;
+    # *)            scratch_installed $@; exit;;
+  esac
+done
 
